CREATE TABLE [dbo].[AspNetRoles](
	[Id] [NVARCHAR](450) NOT NULL,
	[Name] [NVARCHAR](256) NULL,
	[NormalizedName] [NVARCHAR](256) NULL,
	[ConcurrencyStamp] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO