CREATE TABLE [dbo].[DeviceCodes](
	[UserCode] [NVARCHAR](200) NOT NULL,
	[DeviceCode] [NVARCHAR](200) NOT NULL,
	[SubjectId] [NVARCHAR](200) NULL,
	[ClientId] [NVARCHAR](200) NOT NULL,
	[CreationTime] [DATETIME2](7) NOT NULL,
	[Expiration] [DATETIME2](7) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
 CONSTRAINT [PK_DeviceCodes] PRIMARY KEY CLUSTERED 
(
	[UserCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO