CREATE TABLE [dbo].[ResultReferenceRanges]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ResultId] INT NOT NULL, 
    [NormalHighLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1, 
    [NormalLowLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [AttentionHighLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1, 
    [AttentionLowLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [PathologyHighLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1, 
    [PathologyLowLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [AbsoluteDeltaLowLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [AbsoluteDeltaHighLimit] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [RelativeDeltaLow] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [RelativeDeltaHigh] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityAbsoluteLow_DeltaLow] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityAbsoluteLow_DeltaHigh] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityAbsoluteHigh_DeltaLow] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityAbsoluteHigh_DeltaHigh] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityRelativeLow_DeltaLow] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityRelativeLow_DeltaHigh] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityRelativeHigh_DeltaLow] DECIMAL(10, 8) NOT NULL DEFAULT -1,
    [OutOfNormalityRelativeHigh_DeltaHigh] DECIMAL(10, 8) NOT NULL DEFAULT -1, 
    [DeltaValidityDays] INT NOT NULL DEFAULT 0, 
    [BiasFactor] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_ResultReferenceRanges_ResultId] FOREIGN KEY ([ResultId]) REFERENCES [dbo].[Result]([Id]),

    )
