//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CD4.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CD4.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Caption&quot;:&quot;Event Time&quot;,&quot;FieldName&quot;:&quot;CreatedAt&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnCreatedAt&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:0,&quot;Width&quot;:110,&quot;IsSorted&quot;:false,&quot;IsAscending&quot;:false,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;Event Details&quot;,&quot;FieldName&quot;:&quot;Details&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnDetails&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:1,&quot;Width&quot;:300,&quot;IsSorted&quot;:false,&quot;IsAscending&quot;:false,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;CIN&quot;,&quot;FieldName&quot;:&quot;Cin&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnCinAudit&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:2,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuditColumns {
            get {
                return ResourceManager.GetString("AuditColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage dispatchPlane {
            get {
                object obj = ResourceManager.GetObject("dispatchPlane", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string IsMultipleDisciplinesEnabled {
            get {
                return ResourceManager.GetString("IsMultipleDisciplinesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string IsResultAlertEnabledOnReportPrint {
            get {
                return ResourceManager.GetString("IsResultAlertEnabledOnReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage marker {
            get {
                object obj = ResourceManager.GetObject("marker", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage NDATrackingIcon {
            get {
                object obj = ResourceManager.GetObject("NDATrackingIcon", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Caption&quot;:&quot;All Disciplines&quot;,&quot;Image&quot;:&quot;Disciplines&quot;,&quot;Name&quot;:&quot;barButtonItemAllDisciplines&quot;,&quot;Tag&quot;:0},{&quot;Caption&quot;:&quot;Diagnostic Haematology&quot;,&quot;Image&quot;:&quot;Haematology&quot;,&quot;Name&quot;:&quot;barButtonItemHaematology&quot;,&quot;Tag&quot;:1},{&quot;Caption&quot;:&quot;ClinicalPathology&quot;,&quot;Image&quot;:&quot;ClinicalPathology&quot;,&quot;Name&quot;:&quot;barButtonItemClinicalPathology&quot;,&quot;Tag&quot;:4},{&quot;Caption&quot;:&quot;Microbiology&quot;,&quot;Image&quot;:&quot;Microbiology&quot;,&quot;Name&quot;:&quot;barButtonItemMicrobiology&quot;,&quot;Tag&quot;:3},{&quot;Caption&quot;:&quot;Molecular Biology&quot;,&quot;Image&quot;:&quot;Molecular&quot;,&quot;Name&quot;:&quot;barButtonItemMolecular&quot;,&quot;Tag&quot;:2},{&quot;Caption&quot;:&quot;Clinical [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string popupMenuDisciplines {
            get {
                return ResourceManager.GetString("popupMenuDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Caption&quot;:&quot;Seq.&quot;,&quot;FieldName&quot;:&quot;Id&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnSequence&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:0,&quot;Width&quot;:40,&quot;IsSorted&quot;:true,&quot;IsAscending&quot;:true,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;Memo No.&quot;,&quot;FieldName&quot;:&quot;EpisodeNumber&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnEpisodeNumber&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:1,&quot;Width&quot;:100,&quot;IsSorted&quot;:false,&quot;IsAscending&quot;:false,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot; &quot;,&quot;FieldName&quot;:&quot;SamplePriorityIcon&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnSamplePriorityIcon&quot;,&quot;Visible&quot;:true,&quot;Visi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleColumns {
            get {
                return ResourceManager.GetString("SampleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Caption&quot;:&quot;Test&quot;,&quot;FieldName&quot;:&quot;Test&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnTestName&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:0,&quot;Width&quot;:109,&quot;IsSorted&quot;:false,&quot;IsAscending&quot;:false,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot; &quot;,&quot;FieldName&quot;:&quot;StatusIcon&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnStatusIcon&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:1,&quot;Width&quot;:36,&quot;IsSorted&quot;:false,&quot;IsAscending&quot;:false,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;Result&quot;,&quot;FieldName&quot;:&quot;Result&quot;,&quot;AllowEdit&quot;:true,&quot;Name&quot;:&quot;gridColumnResult&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:2,&quot;Width&quot;:109,&quot;IsSo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestColumns {
            get {
                return ResourceManager.GetString("TestColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Caption&quot;:&quot;Seq.&quot;,&quot;FieldName&quot;:&quot;Number&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnNumber&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:0,&quot;Width&quot;:40,&quot;IsSorted&quot;:true,&quot;IsAscending&quot;:true,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;Assay&quot;,&quot;FieldName&quot;:&quot;TestName&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnTestName&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:1,&quot;Width&quot;:100,&quot;IsSorted&quot;:true,&quot;IsAscending&quot;:true,&quot;HeaderGroupIndex&quot;:-1},{&quot;Caption&quot;:&quot;Result&quot;,&quot;FieldName&quot;:&quot;Result&quot;,&quot;AllowEdit&quot;:false,&quot;Name&quot;:&quot;gridColumnResult&quot;,&quot;Visible&quot;:true,&quot;VisibleIndex&quot;:2,&quot;Width&quot;:100,&quot;IsSorte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestHistoryColumns {
            get {
                return ResourceManager.GetString("TestHistoryColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage updateUser {
            get {
                object obj = ResourceManager.GetObject("updateUser", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
    }
}
